plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

repositories {
}

loom {
    accessWidenerPath = file('src/main/resources/realobsidian.accesswidener')
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

processResources {
    inputs.properties([
            version                : project.version,
            mod_id                 : project.mod_id,
            mod_name               : project.mod_name,
            mod_description        : project.mod_description,
            mod_authors            : project.mod_authors,
            mod_license            : project.mod_license,
            loader_version         : project.loader_version,
            minecraft_version_range: project.minecraft_version_range
    ])

    filesMatching('fabric.mod.json') {
        expand(inputs.properties)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    it.options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.name}" }
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url = uri("${project.projectDir}/repo")
        }
    }
}

tasks.withType(JavaExec).configureEach {
    standardInput = System.in
}
