org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.1.1
minecraft_version_range=26.1.x
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

mod_id=realobsidian
mod_name=Real Obsidian
mod_license=BSD 2-Clause (FreeBSD) License
mod_version=1.0.0
mod_group_id=io.github.makaseloli.realobsidian
mod_authors=makaseloli
mod_description=Very simple mod that makes obsidian and crying obsidian behave like glass.
