org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# The Minecraft version must agree with the NeoForge version to get a valid artifact.
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.0.19-beta
neo_version_range=[26.1,26.2)

# Mod Properties
mod_id=realobsidian
mod_name=Real Obsidian
mod_license=BSD 2-Clause (FreeBSD) License
mod_version=1.0.0
mod_group_id=io.github.makaseloli.realobsidian
mod_authors=makaseloli
mod_description=Very simple mod that makes obsidian and crying obsidian behave like glass.
