org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=realobsidian
modName=Real Obsidian
modLicense=BSD 2-Clause License
modGroupId=io.github.makaseloli.realobsidian
modAuthors=makaseloli
modDescription=Very simple mod that makes obsidian and crying obsidian behave like glass.
modDisplayUrl=https://github.com/makaseloli/Real-Obsidian
modIssueTrackerUrl=https://github.com/makaseloli/Real-Obsidian/issues
modCredits=


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=io.github.makaseloli.realobsidian.RealObsidianMod
modFabricClientEntrypoint=
